-- VHDL Entity my_project3_lib.icache2.symbol
--
-- Created:
--          by - mg217.bin (cparch05.ecn.purdue.edu)
--          at - 21:13:26 03/07/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.2 (Build 10)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY icache2 IS
   PORT( 
      clk       : IN     std_logic;
      memins    : IN     std_logic_vector (31 DOWNTO 0);
      dataready : IN     std_logic;
      nrst      : IN     std_logic;
      pc        : IN     std_logic_vector (31 DOWNTO 0);
      ins       : OUT    std_logic_vector (31 DOWNTO 0);
      mempc     : OUT    std_logic_vector (15 DOWNTO 0);
      pcwait    : OUT    std_logic;
      iread     : OUT    std_logic
   );

-- Declarations

END icache2 ;

--
-- VHDL Architecture my_project3_lib.icache2.struct
--
-- Created:
--          by - mg217.bin (cparch05.ecn.purdue.edu)
--          at - 21:13:26 03/07/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.2 (Build 10)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ARCHITECTURE struct OF icache2 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL hit      : std_logic;
   SIGNAL newBlock : std_logic_vector(31 DOWNTO 0);
   SIGNAL wen      : std_logic;


   -- Component Declarations
   COMPONENT cache_ctrl
   PORT (
      clk      : IN     STD_LOGIC;
      hit      : IN     std_logic;
      ins      : IN     std_logic_vector (31 DOWNTO 0);
      nrst     : IN     std_logic;
      request  : IN     STD_LOGIC_VECTOR (31 DOWNTO 0);
      pcwait   : OUT    std_logic;
      newBlock : OUT    std_logic_vector (31 DOWNTO 0);
      pc       : OUT    std_logic_vector (15 DOWNTO 0);
      iread    : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT data_array
   PORT (
      clk  : IN     std_logic;
      nrst : IN     std_logic;
      rsel : IN     std_logic_vector (31 DOWNTO 0);
      wdat : IN     std_logic_vector (31 DOWNTO 0);
      dataready  : IN     std_logic;
      hit  : OUT    std_logic;
      rdat : OUT    std_logic_vector (31 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   -- pragma synthesis_on

BEGIN

   -- Instance port mappings.
   U_0 : cache_ctrl
      PORT MAP (
         request  => pc,
         hit      => hit,
         newBlock => newBlock,
         pcwait   => pcwait,
         pc       => mempc,
         ins      => memins,
         clk      => clk,
         nrst     => nrst,
         iread    => iread
      );
   U_1 : data_array
      PORT MAP (
         wdat => newBlock,
         dataready  => dataready,
         rsel => pc,
         rdat => ins,
         hit  => hit,
         clk  => clk,
         nrst => nrst
      );

END struct;
